
name: Viral Blog Generator

on:
  schedule:
    # Run 4 times per hour (every 15 minutes) for viral content bursts
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-viral-blog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkpoint - Starting viral blog workflow
      run: echo "Starting AI Blog Scribe viral content generation at $(date)"
      
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: automation/package.json
        
    - name: Install dependencies
      working-directory: ./automation
      run: |
        echo "Installing dependencies for viral content generation..."
        npm install
        echo "Dependencies installed successfully"
        
    - name: Verify environment variables
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "Checking viral blog environment variables..."
        if [ -z "$GEMINI_API_KEY" ]; then echo "ERROR: GEMINI_API_KEY is not set"; exit 1; fi
        if [ -z "$GMAIL_EMAIL" ]; then echo "ERROR: GMAIL_EMAIL is not set"; exit 1; fi
        if [ -z "$GMAIL_APP_PASSWORD" ]; then echo "ERROR: GMAIL_APP_PASSWORD is not set"; exit 1; fi
        if [ -z "$RECIPIENT_EMAIL" ]; then echo "ERROR: RECIPIENT_EMAIL is not set"; exit 1; fi
        echo "All environment variables are set for viral content"
        echo "Gmail Email: $GMAIL_EMAIL"
        echo "Recipient Email: $RECIPIENT_EMAIL"
        
    - name: Generate and send viral blog post
      working-directory: ./automation
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "Starting viral blog generation process..."
        node generate-blog.js
        echo "Viral blog generation process completed"

    - name: Log viral content completion
      run: echo "Viral blog generation completed successfully at $(date)"
