
name: Auto Blog Generator

on:
  schedule:
    # Run every 5 minutes for testing (change back to desired frequency later)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkpoint - Starting workflow
      run: echo "Starting AI Blog Scribe automation at $(date)"
      
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: automation/package.json
        
    - name: Install dependencies
      working-directory: ./automation
      run: |
        echo "Installing dependencies..."
        npm install
        echo "Dependencies installed successfully"
        
    - name: Verify environment variables
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        MAILFENCE_EMAIL: ${{ secrets.MAILFENCE_EMAIL }}
        MAILFENCE_PASSWORD: ${{ secrets.MAILFENCE_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "Checking environment variables..."
        if [ -z "$GEMINI_API_KEY" ]; then echo "ERROR: GEMINI_API_KEY is not set"; exit 1; fi
        if [ -z "$MAILFENCE_EMAIL" ]; then echo "ERROR: MAILFENCE_EMAIL is not set"; exit 1; fi
        if [ -z "$MAILFENCE_PASSWORD" ]; then echo "ERROR: MAILFENCE_PASSWORD is not set"; exit 1; fi
        if [ -z "$RECIPIENT_EMAIL" ]; then echo "ERROR: RECIPIENT_EMAIL is not set"; exit 1; fi
        echo "All environment variables are set"
        echo "Mailfence Email: $MAILFENCE_EMAIL"
        echo "Recipient Email: $RECIPIENT_EMAIL"
        
    - name: Generate and send blog post
      working-directory: ./automation
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        MAILFENCE_EMAIL: ${{ secrets.MAILFENCE_EMAIL }}
        MAILFENCE_PASSWORD: ${{ secrets.MAILFENCE_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "Starting blog generation process..."
        node generate-blog.js
        echo "Blog generation process completed"

    - name: Log completion
      run: echo "Blog generation completed successfully at $(date)"
